name: FeatureCI
on:
  push:
    branches:
      - 'source'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ghp and pelican
      run: |
        apt-get install python3-setuptools
        pip3 install pelican ghp-import 
    - name: Run a make html
      run: |
        pelican content -o output -s pelicanconf.py
        ghp-import output -b gh-pages
        git push git@github.com:andrewelkins/andrewelkins.github.io.git gh-pages:master
